// flow-typed signature: 2b98537f4e54d4bc444f871e3db15f25
// flow-typed version: <<STUB>>/fly-watch_v^1.1.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fly-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fly-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fly-watch/index' {
  declare module.exports: $Exports<'fly-watch'>;
}
declare module 'fly-watch/index.js' {
  declare module.exports: $Exports<'fly-watch'>;
}
