// flow-typed signature: bb4435924bdbe13a9f08d066814c64d7
// flow-typed version: <<STUB>>/fly-clear_v^1.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fly-clear'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fly-clear' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fly-clear/index' {
  declare module.exports: $Exports<'fly-clear'>;
}
declare module 'fly-clear/index.js' {
  declare module.exports: $Exports<'fly-clear'>;
}
