// flow-typed signature: d51816d5b44202630a17fcd1f368c604
// flow-typed version: <<STUB>>/fly-prettier_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fly-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fly-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fly-prettier/index' {
  declare module.exports: $Exports<'fly-prettier'>;
}
declare module 'fly-prettier/index.js' {
  declare module.exports: $Exports<'fly-prettier'>;
}
