// flow-typed signature: ab9ada9a6bd76650ebf4d53f42ef8a1f
// flow-typed version: <<STUB>>/fly-unflow_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fly-unflow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fly-unflow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fly-unflow/index' {
  declare module.exports: $Exports<'fly-unflow'>;
}
declare module 'fly-unflow/index.js' {
  declare module.exports: $Exports<'fly-unflow'>;
}
