// flow-typed signature: 82d6b4b09be3269473a0e3b2dabf7e85
// flow-typed version: <<STUB>>/fly-jest_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fly-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fly-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fly-jest/index' {
  declare module.exports: $Exports<'fly-jest'>;
}
declare module 'fly-jest/index.js' {
  declare module.exports: $Exports<'fly-jest'>;
}
