// flow-typed signature: 09e6996ed58bad2f56d51d34b746359b
// flow-typed version: <<STUB>>/fly-esnext_v^2.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fly-esnext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fly-esnext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fly-esnext/test/fixtures/flyfile' {
  declare module.exports: any;
}

declare module 'fly-esnext/test/fixtures/foo' {
  declare module.exports: any;
}

declare module 'fly-esnext/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fly-esnext/index' {
  declare module.exports: $Exports<'fly-esnext'>;
}
declare module 'fly-esnext/index.js' {
  declare module.exports: $Exports<'fly-esnext'>;
}
declare module 'fly-esnext/test/fixtures/flyfile.js' {
  declare module.exports: $Exports<'fly-esnext/test/fixtures/flyfile'>;
}
declare module 'fly-esnext/test/fixtures/foo.js' {
  declare module.exports: $Exports<'fly-esnext/test/fixtures/foo'>;
}
declare module 'fly-esnext/test/index.js' {
  declare module.exports: $Exports<'fly-esnext/test/index'>;
}
