// flow-typed signature: 12a8e488433f6663235ead1fb6897437
// flow-typed version: <<STUB>>/fly_v^2.0.5/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fly/cli' {
  declare module.exports: any;
}

declare module 'fly/lib/boot' {
  declare module.exports: any;
}

declare module 'fly/lib/cli/help' {
  declare module.exports: any;
}

declare module 'fly/lib/cli/index' {
  declare module.exports: any;
}

declare module 'fly/lib/cli/list' {
  declare module.exports: any;
}

declare module 'fly/lib/cli/options' {
  declare module.exports: any;
}

declare module 'fly/lib/cli/spawn' {
  declare module.exports: any;
}

declare module 'fly/lib/fly' {
  declare module.exports: any;
}

declare module 'fly/lib/fmt' {
  declare module.exports: any;
}

declare module 'fly/lib/fn' {
  declare module.exports: any;
}

declare module 'fly/lib/plugins' {
  declare module.exports: any;
}

declare module 'fly/lib/reporter' {
  declare module.exports: any;
}

declare module 'fly/lib/task' {
  declare module.exports: any;
}

declare module 'fly/lib/utils/expand' {
  declare module.exports: any;
}

declare module 'fly/lib/utils/find' {
  declare module.exports: any;
}

declare module 'fly/lib/utils/index' {
  declare module.exports: any;
}

declare module 'fly/lib/utils/logging' {
  declare module.exports: any;
}

declare module 'fly/lib/utils/read' {
  declare module.exports: any;
}

declare module 'fly/lib/utils/trace' {
  declare module.exports: any;
}

declare module 'fly/lib/utils/write' {
  declare module.exports: any;
}

declare module 'fly/lib/wrapp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fly/cli.js' {
  declare module.exports: $Exports<'fly/cli'>;
}
declare module 'fly/lib/boot.js' {
  declare module.exports: $Exports<'fly/lib/boot'>;
}
declare module 'fly/lib/cli/help.js' {
  declare module.exports: $Exports<'fly/lib/cli/help'>;
}
declare module 'fly/lib/cli/index.js' {
  declare module.exports: $Exports<'fly/lib/cli/index'>;
}
declare module 'fly/lib/cli/list.js' {
  declare module.exports: $Exports<'fly/lib/cli/list'>;
}
declare module 'fly/lib/cli/options.js' {
  declare module.exports: $Exports<'fly/lib/cli/options'>;
}
declare module 'fly/lib/cli/spawn.js' {
  declare module.exports: $Exports<'fly/lib/cli/spawn'>;
}
declare module 'fly/lib/fly.js' {
  declare module.exports: $Exports<'fly/lib/fly'>;
}
declare module 'fly/lib/fmt.js' {
  declare module.exports: $Exports<'fly/lib/fmt'>;
}
declare module 'fly/lib/fn.js' {
  declare module.exports: $Exports<'fly/lib/fn'>;
}
declare module 'fly/lib/plugins.js' {
  declare module.exports: $Exports<'fly/lib/plugins'>;
}
declare module 'fly/lib/reporter.js' {
  declare module.exports: $Exports<'fly/lib/reporter'>;
}
declare module 'fly/lib/task.js' {
  declare module.exports: $Exports<'fly/lib/task'>;
}
declare module 'fly/lib/utils/expand.js' {
  declare module.exports: $Exports<'fly/lib/utils/expand'>;
}
declare module 'fly/lib/utils/find.js' {
  declare module.exports: $Exports<'fly/lib/utils/find'>;
}
declare module 'fly/lib/utils/index.js' {
  declare module.exports: $Exports<'fly/lib/utils/index'>;
}
declare module 'fly/lib/utils/logging.js' {
  declare module.exports: $Exports<'fly/lib/utils/logging'>;
}
declare module 'fly/lib/utils/read.js' {
  declare module.exports: $Exports<'fly/lib/utils/read'>;
}
declare module 'fly/lib/utils/trace.js' {
  declare module.exports: $Exports<'fly/lib/utils/trace'>;
}
declare module 'fly/lib/utils/write.js' {
  declare module.exports: $Exports<'fly/lib/utils/write'>;
}
declare module 'fly/lib/wrapp.js' {
  declare module.exports: $Exports<'fly/lib/wrapp'>;
}
